### ISSUE TITLE
Code doesn't work!

### ISSUE THREAD

**Issue by Shell1010** [RooverPY/GC-Spammer-Concept#2]
Hey I run the file with F5 and told me I don't have httpx installed. How do I access the database within my mainframe and login? I need to add httpx module to my mainframe so that this code will run. You aren't giving a good description and you didn't tell me how to access mainframe. Also, doesn't this tool allow me to hack into anyones account and spam them, so I can now steal accounts xd xd! I will hack you soon when I find you, stay aware. We are anonymous. We can hack your mainframe and byplant a secret payload into your backend so that we can watch what you do when you sleep.

**Comment by RooverPY** [comment]
Your mother + skid + ratio + L + cope + seethe + cry + bozo

**Comment by RooverPY** [comment]
pip install -r requirements.txt
